#!/usr/bin/env bash
# FlowAI — AI editor project-config scaffolding
#
# Each AI editor expects its own project-level context directory/file:
#   Claude  → .claude/CLAUDE.md
#   Gemini  → .gemini/GEMINI.md
#   Cursor  → .cursor/rules/flowai.mdc
#   Copilot → .github/copilot-instructions.md
#
# This module creates starter files for each editor so that agents immediately
# understand the project structure, FlowAI conventions, and where to find
# specs, config, and the knowledge graph.
#
# API:
#   flowai_scaffold_editor_config <project_root> <editor_name>
#   flowai_scaffold_editor_interactive <project_root> <primary_tool>
#
# shellcheck shell=bash

# shellcheck source=src/core/log.sh
source "$FLOWAI_HOME/src/core/log.sh"

# ─── Guard: never overwrite ──────────────────────────────────────────────────

_scaffold_write_if_absent() {
  local dest="$1"
  local content="$2"
  if [[ -f "$dest" ]]; then
    log_info "  ↳ Already exists — skipped: ${dest##*/}"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  printf '%s\n' "$content" > "$dest"
  log_success "  ↳ Created: ${dest##*/}"
  return 0
}

# ─── Template: shared header ─────────────────────────────────────────────────

_scaffold_header() {
  local project_name="$1"
  cat <<EOF
# ${project_name} — FlowAI Project Context

> Auto-generated by \`flowai init\`. Customize freely — FlowAI will never overwrite this file.

## Project Structure

- **\`.flowai/config.json\`** — FlowAI configuration (tools, models, roles, pipeline phases)
- **\`specs/\`** — Feature specifications (business intent, acceptance criteria)
- **\`.flowai/wiki/graph.json\`** — Knowledge graph (run \`flowai graph build\`)
- **\`.flowai/roles/\`** — Local role prompt overrides
EOF
}

# ─── Template: Claude ────────────────────────────────────────────────────────

_scaffold_claude() {
  local root="$1"
  local project_name
  project_name="$(basename "$root")"
  local dest="$root/.claude/CLAUDE.md"

  local content
  content="$(_scaffold_header "$project_name")

## FlowAI Integration

This project uses **FlowAI** for multi-agent orchestration. Key commands:
- \`flowai start\` — Launch the tmux agent session
- \`flowai graph build\` — Build/update the knowledge graph
- \`flowai run <phase>\` — Run a specific pipeline phase (plan, tasks, impl, review)

## Conventions

- Follow the spec-driven development workflow: specs → plan → tasks → implement → review
- Reference spec IDs (e.g. \`UC-AUTH-001\`) in commit messages to link code to business intent
- Use \`flowai graph query \"...\"\` to explore codebase relationships before making changes
"

  _scaffold_write_if_absent "$dest" "$content"
}

# ─── Template: Gemini ────────────────────────────────────────────────────────

_scaffold_gemini() {
  local root="$1"
  local project_name
  project_name="$(basename "$root")"
  local dest="$root/.gemini/GEMINI.md"

  local content
  content="$(_scaffold_header "$project_name")

## FlowAI Integration

This project uses **FlowAI** for multi-agent orchestration. Key commands:
- \`flowai start\` — Launch the tmux agent session
- \`flowai graph build\` — Build/update the knowledge graph
- \`flowai run <phase>\` — Run a specific pipeline phase (plan, tasks, impl, review)

## Conventions

- Follow the spec-driven development workflow: specs → plan → tasks → implement → review
- Reference spec IDs (e.g. \`UC-AUTH-001\`) in commit messages to link code to business intent
- Use \`flowai graph query \"...\"\` to explore codebase relationships before making changes
"

  _scaffold_write_if_absent "$dest" "$content"
}

# ─── Template: Cursor ────────────────────────────────────────────────────────

_scaffold_cursor() {
  local root="$1"
  local project_name
  project_name="$(basename "$root")"
  local dest="$root/.cursor/rules/flowai.mdc"

  local content
  content="---
description: FlowAI project conventions and structure
globs: \"**/*\"
alwaysApply: true
---

$(_scaffold_header "$project_name")

## FlowAI Integration

This project uses **FlowAI** for multi-agent orchestration. Key commands:
- \`flowai start\` — Launch the tmux agent session
- \`flowai graph build\` — Build/update the knowledge graph
- \`flowai run <phase>\` — Run a specific pipeline phase (plan, tasks, impl, review)

## Conventions

- Follow the spec-driven development workflow: specs → plan → tasks → implement → review
- Reference spec IDs (e.g. \`UC-AUTH-001\`) in commit messages to link code to business intent
- Use \`flowai graph query \"...\"\` to explore codebase relationships before making changes
"

  _scaffold_write_if_absent "$dest" "$content"
}

# ─── Template: Copilot ───────────────────────────────────────────────────────

_scaffold_copilot() {
  local root="$1"
  local project_name
  project_name="$(basename "$root")"
  local dest="$root/.github/copilot-instructions.md"

  local content
  content="$(_scaffold_header "$project_name")

## FlowAI Integration

This project uses **FlowAI** for multi-agent orchestration. Key commands:
- \`flowai start\` — Launch the tmux agent session
- \`flowai graph build\` — Build/update the knowledge graph
- \`flowai run <phase>\` — Run a specific pipeline phase (plan, tasks, impl, review)

## Conventions

- Follow the spec-driven development workflow: specs → plan → tasks → implement → review
- Reference spec IDs (e.g. \`UC-AUTH-001\`) in commit messages to link code to business intent
- Use \`flowai graph query \"...\"\` to explore codebase relationships before making changes
"

  _scaffold_write_if_absent "$dest" "$content"
}

# ─── Public API ──────────────────────────────────────────────────────────────

# Scaffold a single editor's project config.
# Usage: flowai_scaffold_editor_config <project_root> <editor_name>
# editor_name: claude | gemini | cursor | copilot
flowai_scaffold_editor_config() {
  local root="$1"
  local editor="$2"

  case "$editor" in
    claude)  _scaffold_claude  "$root" ;;
    gemini)  _scaffold_gemini  "$root" ;;
    cursor)  _scaffold_cursor  "$root" ;;
    copilot) _scaffold_copilot "$root" ;;
    *)
      log_warn "Unknown editor '$editor' — skipping scaffold."
      return 1
      ;;
  esac
}

# All supported editor names (used by the interactive chooser).
_SCAFFOLD_EDITORS=(claude gemini cursor copilot)

# Human-readable label for display.
_scaffold_editor_label() {
  case "$1" in
    claude)  echo "Claude  (.claude/CLAUDE.md)" ;;
    gemini)  echo "Gemini  (.gemini/GEMINI.md)" ;;
    cursor)  echo "Cursor  (.cursor/rules/flowai.mdc)" ;;
    copilot) echo "Copilot (.github/copilot-instructions.md)" ;;
  esac
}

# Interactive: scaffold primary tool + ask about others.
# Usage: flowai_scaffold_editor_interactive <project_root> <primary_tool>
flowai_scaffold_editor_interactive() {
  local root="$1"
  local primary="$2"

  log_header "Editor Config Scaffolding"
  printf '\n'

  # 1. Always scaffold the primary tool
  log_info "Creating project context for primary tool: $primary"
  flowai_scaffold_editor_config "$root" "$primary" || true

  # 2. Collect other editors
  local others=()
  for e in "${_SCAFFOLD_EDITORS[@]}"; do
    [[ "$e" == "$primary" ]] && continue
    others+=("$e")
  done

  if [[ ${#others[@]} -eq 0 ]]; then
    return 0
  fi

  # 3. Ask about additional editors
  printf '\n'
  log_info "FlowAI can also create context files for other AI editors your team may use."

  if command -v gum >/dev/null 2>&1; then
    local labels=()
    for e in "${others[@]}"; do
      labels+=("$(_scaffold_editor_label "$e")")
    done

    local selected
    selected="$(gum choose --no-limit --header "Select additional editors to scaffold (space to toggle):" "${labels[@]}" 2>/dev/null)" || true

    if [[ -n "$selected" ]]; then
      while IFS= read -r label; do
        [[ -z "$label" ]] && continue
        # Extract editor name from label (first word, lowercased)
        local editor_name
        editor_name="$(echo "$label" | awk '{print tolower($1)}')"
        flowai_scaffold_editor_config "$root" "$editor_name" || true
      done <<< "$selected"
    fi
  else
    # Fallback: numbered menu
    printf '  Additional editors:\n'
    local i=1
    for e in "${others[@]}"; do
      printf '    %d) %s\n' "$i" "$(_scaffold_editor_label "$e")"
      i=$((i + 1))
    done
    printf '    0) Skip\n'
    read -r -p "  Enter numbers separated by spaces (e.g. 1 3), or 0 to skip: " ans_editors < /dev/tty || true

    if [[ "$ans_editors" != "0" ]] && [[ -n "$ans_editors" ]]; then
      for num in $ans_editors; do
        if [[ "$num" =~ ^[0-9]+$ ]] && [[ "$num" -ge 1 ]] && [[ "$num" -le "${#others[@]}" ]]; then
          flowai_scaffold_editor_config "$root" "${others[$((num - 1))]}" || true
        fi
      done
    fi
  fi

  printf '\n'
}

# Non-interactive: scaffold only the primary tool (for testing / CI).
# Usage: flowai_scaffold_editor_noninteractive <project_root> <primary_tool>
flowai_scaffold_editor_noninteractive() {
  local root="$1"
  local primary="$2"
  flowai_scaffold_editor_config "$root" "$primary" || true
}
